export const blogPosts = [
    {
        id: "getting-started-with-nextjs",
        title: "Getting Started with Next.js: A Comprehensive Guide",
        excerpt: "Learn how to build modern web applications with Next.js, from setup to deployment.",
        coverImage: "/placeholder.svg?height=400&width=600",
        readTime: 8,
        date: "May 15, 2024",
        author: {
            name: "Sarah Johnson",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        tags: ["Next.js", "React", "Tutorial"],
    },
    {
        id: "mastering-tailwind-css",
        title: "Mastering Tailwind CSS: Tips and Tricks",
        excerpt: "Discover advanced techniques to make the most out of Tailwind CSS in your projects.",
        coverImage: "/placeholder.svg?height=400&width=600",
        readTime: 6,
        date: "May 10, 2024",
        author: {
            name: "Michael Chen",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        tags: ["CSS", "Tailwind", "Design"],
    },
    {
        id: "server-components-explained",
        title: "React Server Components Explained",
        excerpt: "A deep dive into React Server Components and how they change the way we build applications.",
        coverImage: "/placeholder.svg?height=400&width=600",
        readTime: 10,
        date: "May 5, 2024",
        author: {
            name: "Alex Rodriguez",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        tags: ["React", "Server Components", "Performance"],
    },
    {
        id: "building-accessible-uis",
        title: "Building Accessible UIs with shadcn/ui",
        excerpt: "Learn how to create inclusive user interfaces using shadcn/ui components.",
        coverImage: "/placeholder.svg?height=400&width=600",
        readTime: 7,
        date: "April 28, 2024",
        author: {
            name: "Emma Wilson",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        tags: ["Accessibility", "UI", "shadcn"],
    },
    {
        id: "state-management-2024",
        title: "State Management in 2024: What's New?",
        excerpt: "Explore the latest trends and tools for managing state in modern web applications.",
        coverImage: "/placeholder.svg?height=400&width=600",
        readTime: 9,
        date: "April 22, 2024",
        author: {
            name: "David Kim",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        tags: ["State Management", "React", "JavaScript"],
    },
    {
        id: "optimizing-images-nextjs",
        title: "Optimizing Images in Next.js Applications",
        excerpt: "Best practices for handling and optimizing images in your Next.js projects.",
        coverImage: "/placeholder.svg?height=400&width=600",
        readTime: 5,
        date: "April 18, 2024",
        author: {
            name: "Priya Patel",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        tags: ["Performance", "Images", "Next.js"],
    },
    {
        id: "typescript-best-practices",
        title: "TypeScript Best Practices for 2024",
        excerpt: "Stay up-to-date with the latest TypeScript patterns and practices for better code quality.",
        coverImage: "/placeholder.svg?height=400&width=600",
        readTime: 8,
        date: "April 12, 2024",
        author: {
            name: "James Wilson",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        tags: ["TypeScript", "Best Practices", "Development"],
    },
    {
        id: "serverless-functions-guide",
        title: "The Ultimate Guide to Serverless Functions",
        excerpt: "Everything you need to know about building and deploying serverless functions.",
        coverImage: "/placeholder.svg?height=400&width=600",
        readTime: 11,
        date: "April 5, 2024",
        author: {
            name: "Sophia Martinez",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        tags: ["Serverless", "Cloud", "Backend"],
    },
]
